-- DATABASE INITIALIZATION SCRIPT

-- Create the normal tables
CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL
);

CREATE TABLE products (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  price DECIMAL(10, 2) NOT NULL
);

-- Create the JSON store
CREATE TABLE json_store (
  id SERIAL PRIMARY KEY,
  data JSONB NOT NULL
);